# SwiftLint configuration

# Paths to include
included:
  - SwiftMarkdown
  - SwiftMarkdownCore
  - SwiftMarkdownTests
  - SwiftMarkdownQuickLook

# Paths to exclude
excluded:
  - DerivedData
  - .build
  - Pods
  - Carthage

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - todo  # TODOs are expected placeholders in skeleton code

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 1000

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

reporter: xcode
